on:
  push:
    branches: [ FinalProjectCorrection ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout ğŸ›ï¸
          uses: actions/checkout@master

        - name: Go to Front â†ª
          run: cd Front

        - name: Run cypress tests â–¶
          uses: cypress-io/github-action@v2
          with:
            start: |
              npm start
            wait-on: 'http://localhost:3000'
            config: baseUrl=https://localhost:3000

        - name: React Test âš™ (npm ci, build and test)
          run: |
            npm ci
            npm run build --if-present
            npm test    

        - name: Go to Back â†ª
          run: |
            cd ..
            cd Back

        - name: Init Composer for test ğŸ”§ 
          uses: php-actions/composer@v5

        - name: Run phpunit tests â–¶ 
          uses: php-actions/phpunit@v3
          with: 
            start: cd Back
       
