on:
  push:
    branches: [ FinalProjectCorrection ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout ğŸ›ï¸
          uses: actions/checkout@master

        - name: Run cypress tests â–¶
          working-directory: ./Front
          uses: cypress-io/github-action@v2
          with:
            start: |
              npm start
            wait-on: 'http://localhost:3000'
            config: baseUrl=https://localhost:3000

        - name: React Test âš™ (npm ci, build and test)
          working-directory: ./Front
          run: |
            npm ci
            npm run build --if-present
            npm test    

        - name: Init Composer for test ğŸ”§ 
          working-directory: ./Back
          uses: php-actions/composer@v5

        - name: Run phpunit tests â–¶ 
          working-directory: ./Back
          uses: php-actions/phpunit@v3
          
       
